var map,infoWindow,marker,province,premier={Ontario:"Doug Ford",Quebec:"Francois Legault","Nova Scotia":"Stephen McNeil","New Brunswick":"Blaine Higgs",Manitoba:"Brian Pallister","British Columbia":"John Horgan","Prince Edward Island":"Dennis King",Saskatchewan:"Scott Moe",Alberta:"Jason Kenney","Newfoundland and Labrador":"Dwight Ball"},provtax={Ontario:"13%",Quebec:"14.975%","Nova Scotia":"15%","New Brunswick":"15%",Manitoba:"13%","British Columbia":"12%","Prince Edward Island":"15%",Saskatchewan:"11%",
Alberta:"5%","Newfoundland and Labrador":"15%"},provattr={Ontario:'<a href="https://niagarafalls.ca" target="_blank">Niagara Falls</a>',Quebec:'<a href="http://holydoorquebec.ca/en" target="_blank">Notre-Dame-de-Quebec Basilica-Cathedral</a>',"Nova Scotia":'<a href="https://www.cbisland.com" target="_blank">Cape Breton Island</a>',"New Brunswick":'<a href="https://www.tourismnewbrunswick.ca/See/BayOfFundy/" target="_blank">Bay of Fundy</a>',Manitoba:'<a href="https://www.theforks.com" target="_blank">The Forks</a>',
"British Columbia":'<a href="https://www.tourismvictoria.com/see-do/whale-watching?gclid=Cj0KCQjw9pDpBRCkARIsAOzRziunbF0CINNHBoISDqJqMp2sH9JcMyvg8QvMMLXMReYuJsF71MTaXFcaAlkTEALw_wcB" target="_blank">Victoria B.C. Whale Watching</a>',"Prince Edward Island":'<a href="https://www.pc.gc.ca/en/lhn-nhs/pe/greengables" target="_blank">Green Gables Heritage Place</a>',Saskatchewan:'<a href="https://www.pc.gc.ca/en/pn-np/sk/princealbert" target="_blank">Prince Albert National Park</a>',Alberta:'<a href="https://www.pc.gc.ca/en/pn-np/ab/banff" target="_blank">Banff National Park</a>',
"Newfoundland and Labrador":'<a href="https://www.pc.gc.ca/en/pn-np/nl/grosmorne" target="_blank">Gros Morne National Park</a>'},provattrkids={Ontario:'<a href="https://www.toronto.ca/explore-enjoy/parks-gardens-beaches/toronto-island-park" target="_blank">Toronto Island Park</a>',Quebec:'<a href="https://www.sepaq.com/ct/paq" target="_blank">Aquarium of Quebec</a>',"Nova Scotia":'<a href="https://thediscoverycentre.ca" target="_blank">Discovery Centre</a>',"New Brunswick":'<a href="https://www.huntsmanmarine.ca/fundy-discovery-aquarium" target="_blank">Fundy Dicovery Aquarium</a>',
Manitoba:'<a href="https://www.assiniboineparkzoo.ca" target="_blank">Assiniboine Park Zoo</a>',"British Columbia":'<a href="http://kidsmarket.ca" target="_blank">Kids Market</a>',"Prince Edward Island":'<a href="https://www.islandhillfarm.ca" target="_blank">Island Hill Farm</a>',Saskatchewan:'<a href="https://www.sasksciencecentre.com" target="_blank">Saskatchewan Science Centre</a>',Alberta:'<a href="https://www.blackfalds.com/tourism-recreation/abbey-centre" target="_blank">Abbey Centre</a>',
"Newfoundland and Labrador":'<a href="https://www.pc.gc.ca/fr/lhn-nhs/nl/meadows" target="_blank">L\'Anse aux Meadows National Historic Site</a>'};
function selectProvince(){var a=document.getElementById("s").value;""===a?document.getElementById("map_id").removeAttribute("style"):(province=a,a=document.createElement("script"),a.type="text/javascript",a.src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpnAroegDOkK7_p7IW-niAbkPx3ZFJDS0&callback=loadProvMap",document.getElementsByTagName("head")[0].appendChild(a))}
function printProvInfo(){document.getElementById("prov_info").style.display="block";document.getElementById("provname").innerHTML="&nbsp;&nbsp;&nbsp;Province Name: "+province;document.getElementById("provpremier").innerHTML="&nbsp;&nbsp;&nbsp;Province Premier: "+premier[province];document.getElementById("provtax").innerHTML="&nbsp;&nbsp;&nbsp;Provincial Tax Rate: "+provtax[province];var a=document.getElementById("userage").value;16>=parseInt(a)?document.getElementById("provattr").innerHTML="&nbsp;&nbsp;&nbsp;Provincial Attraction: "+
provattrkids[province]:document.getElementById("provattr").innerHTML="&nbsp;&nbsp;&nbsp;Provincial Attraction: "+provattr[province]}
function loadProvMap(){map=new google.maps.Map(document.getElementById("map_id"),{center:{lat:56.1303673,lng:-106.3467712},zoom:16});(new google.maps.Geocoder).geocode({address:province+" Parliament"},function(a,b){"OK"==b?(map.setCenter(a[0].geometry.location),new google.maps.Marker({map:map,position:a[0].geometry.location}),printProvInfo()):alert("Geocode was not successful for the following reason: "+b)})}
function buttonClicked(){if(navigator.geolocation){var a=document.createElement("script");a.type="text/javascript";a.src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpnAroegDOkK7_p7IW-niAbkPx3ZFJDS0&callback=initMap";document.getElementsByTagName("head")[0].appendChild(a)}else document.getElementById("nogeoloc").style.display="block"}
function printMap(a){map=new google.maps.Map(document.getElementById("map_id"),{center:{lat:56.1303673,lng:-106.3467712},zoom:10});a={lat:a.coords.latitude,lng:a.coords.longitude};map.setCenter(a);marker=new google.maps.Marker({position:a,map:map});(new google.maps.Geocoder).geocode({location:a},function(a,c){if("OK"===c)if(a[8]){var b=a.length-1;do{b--;var d=a[b].formatted_address.split(",",2)}while(2>d.length&&"Canada"!=d[1]);province=d[0];printProvInfo()}else window.alert("No results found");else window.alert("Geocoder failed due to: "+
c)})}function initMap(){infoWindow=new google.maps.InfoWindow;navigator.geolocation?navigator.geolocation.getCurrentPosition(printMap,function(){map=new google.maps.Map(document.getElementById("map_id"),{center:{lat:56.1303673,lng:-106.3467712},zoom:10});handleLocationError(!0,infoWindow,map.getCenter())}):(map=new google.maps.Map(document.getElementById("map_id"),{center:{lat:56.1303673,lng:-106.3467712},zoom:10}),handleLocationError(!1,infoWindow,map.getCenter()))}
function handleLocationError(a,b,c){b.setPosition(c);a=a?"Error: The Geolocation service failed.":"Error: Your browser doesn't support geolocation.";b.setContent(a);b.open(map);window.alert(a)};